exp_id: base
tasks: all
bs: 8
epochs: 50
num_workers: 8
sample_distribution_mode: task_uniform
resume: last
lr: 1.25e-5
warmup_steps: 2000
optimizer_type: lamb
lr_cos_dec: True
transform_augmentation_xyz: [0.125, 0.125, 0.125]
transform_augmentation_rpy: [0.0, 0.0, 45.0]
amp: True
bnb: True
lambda_weight_l2: 1e-4
place_with_mean: False
img_aug: 0.0
noise_type: none
model:
  norm_corr: True
  rend_three_views: True
  img_size: 224
  xops: True
  st_wpt_loc_inp_no_noise: True
  im_channels: 128
  proprio_cat_dim: 64
  lang_dim: 512
  reenc_text: False
  sem_enc_type: CLIP-RN101
  geo_enc_type: RN50
  dep_exp_type: 'DA-vitb'
  dep_exp_path: '/data/ckpt/spact/pretrained'
  align_loss: 0.0
